# Unix Shell {.unnumbered}

The Unix shell has existed for longer than the majority of its users have. It has endured for so long because it is a powerful tool that enables users to complete complicated tasks with a minimal number of keystrokes. More importantly, it makes it possible for users to integrate already-existing programs in novel ways and automate monotonous chores so they won't have to repeatedly type the same things. The shell must be used in order to utilize many other potent tools and computational resources, such as supercomputers used for "high-performance computing." These classes will put you on the right path to efficiently utilizing these resources.

You will learn the fundamentals of file systems and the shell in this session. You are prepared for this course if you have ever stored files on a computer and are familiar with the terms "file," "directory," or "folder" (two common names for the same thing).

A shell is just another type of program. It is unique in that its function is to execute other programs rather than carry out calculations on its own. The Bourne Again SHell, or Bash (so named because it was evolved from a shell created by Stephen Bourne), is the most widely used Unix shell. The default shell on the majority of contemporary Unix systems and in the majority of Windows packages that offer Unix-like features uses the name Bash.

The Unix shell has existed for longer than the majority of its users have. It has endured for so long because it is a powerful tool that enables users to complete complicated tasks with a minimal number of keystrokes. More importantly, it makes it possible for users to integrate already-existing programs in novel ways and automate monotonous chores so they won't have to repeatedly type the same things. The shell must be used in order to utilize many other potent tools and computational resources, such as supercomputers used for "high-performance computing." These classes will put you on the right path to efficiently utilizing these resources.
